PLAINTEXT_VARIABLES:
  SIERRA_BASE: ##
  QA_USERNAME: ##
  QA_PASSWORD: ##
  NYPL_HEADER_URL: ##
  SOURCE_EMAIL: ##
  LIB_ANSWERS_EMAIL: ##
  LOG_LEVEL: ##

ENCRYPTED_VARIABLES:
  PLATFORM_API_CLIENT_ID: ##
  PLATFORM_API_CLIENT_SECRET: ##
  SIERRA_KEY: ##
  SIERRA_SECRET: ##
