PLAINTEXT_VARIABLES:
  SIERRA_BASE: https://nypl.iii.com:443/iii/sierra-api/v6/
  QA_USERNAME:
  QA_PASSWORD:
  NYPL_HEADER_URL: https://ds-header.nypl.org
  LOG_LEVEL: INFO

ENCRYPTED_VARIABLES:
  PLATFORM_API_CLIENT_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGYwZAYJKoZIhvcNAQcGoFcwVQIBADBQBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCyXIiFBZbRP/FJ27gIBEIAjksWZdltNLVeLRVZ/W+7z75PZX7jsj4hzC/c14EuqcxwCgBQ=.
  PLATFORM_API_CLIENT_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAztaE3CPBy+qivgdsMCARCAQ2QfBKCjEGtbFavyAIQtzL2PQ6NwnT7d6R1I7ft7iOmyWzN24IBx5VBgpndCF1tUsI5Fcp8i/IsvvJH39t+M2IGw5Kw=
  SIERRA_KEY: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDIGRaf6BCpFZlCittwIBEIA3U4Xmzt5JgMtzWnmTuQyPOSjnxjyY54t/mL6VyJKO/3s5/0S0B9RivUB9nDDqLGwgeawC6o1L4g==
  SIERRA_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBCefkp/TW7Av59urAIBEIAnBmm5Aug2/CB5cVk4XdlDmvRrQ2y4LC2dmeauT0OjOEZZ9FhRhdvx
